
const recordData = {
    "recording" : [
        {
            id:1,
            date: "12-02-2020",
            time: "9:30 AM",
            pondID: 2321,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"2mm",
            kgOfFeed: 200,
           
        },
        {
            id:2,
            date: "10-02-2020",
            time: "9:30 AM",
            pondID: 2342,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"4mm",
            kgOfFeed:350,
        },
        {
            id:3,
            date: "08-02-2020",
            time: "9:30 AM",
            pondID: 1232,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"6mm",
            kgOfFeed: 450,
        },
        {
            id:4,
            date: "01-02-2020",
            time: "9:30 AM",
            pondID: 5432,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 200,
        },
        {
            id:5,
            date: "15-01-2020",
            time: "9:30 AM",
            pondID: 7653,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"12mm",
            kgOfFeed: 500,
        },
        {
            id:6,
            date: "05-01-2020",
            time: "9:30 AM",
            pondID: 4566,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 90,
        },

        {
            id:7,
            date: "02-01-2020",
            time: "9:30 AM",
            pondID: 2321,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 600,
        },

        {
            id:8,
            date: "19-12-2019",
            time: "9:30 AM",
            pondID:  2342,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 1000,
        },
        {
            id:9,
            date: "12-11-2019",
            time: "9:30 AM",
            pondID: 12345,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 750,
        },
        {
            id:10,
            date: "19-09-2019",
            time: "9:30 AM",
            pondID: 5876,
            typeOfFeed: "Floating pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 300,
        },
    
        {
            id:11,
            date: "09-06-2019",
            time: "9:30 AM",
            pondID: 1223,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 2500,
        },

        {
            id:12,
            date: "02-05-2019",
            time: "9:30 AM",
            pondID: 1233,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 1500,
        },
        {
            id:13,
            date: "02-05-2019",
            time: "9:30 AM",
            pondID: 1232,
            typeOfFeed: "Sinking pallet",
            sizeOfFeed:"9mm",
            kgOfFeed: 400,
        },
    ],
}

export default recordData 