const outboundData = {
  mailserver: [
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
  
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
  
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Test Email",
    },
  ],
  sms: [
    {
      smsProvider: "Oluadepe",
      user: "George Lindrof",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Michael Campbell",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Nick Manis",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Michael Josh",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Hattam Asiani",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Taron Mansoori",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Vishal Pandey",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Andy Migel",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Eric Dyer",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "John Doe",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Shehzad Aslam",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Marqueze Browniee",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
    {
      smsProvider: "Oluadepe",
      user: "Josh Fringer",
      password: "*********",
      apiKey: "my_api_key",
      testSMS: "Test SMS",
    },
  ],
  calls: [
    {
      provider: "Oluadepe",
      user: "George Lindrof",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Michael Campbell",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Nick Manis",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Michael Josh",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Hattam Asiani",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Taron Mansoori",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Vishal Pandey",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Andy Migel",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Eric Dyer",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "John Doe",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Shehzad Aslam",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Marqueze Browniee",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
    {
      provider: "Oluadepe",
      user: "Josh Fringer",
      password: "*********",
      apiKey: "my_api_key",
      testCall: "Test Call",
    },
  ],
};

export default outboundData; 