const harvestData = {
  recording: [
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
    {
      collectionID: 233,
      referenceNo: 233,
      offtakerID: 233,
      group: "Group i",
      famerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      traceabiilityCode: 12235,
      kgCollected: 200,
      pricePerKg: "20,000 NGN",
      totalValue: 12235,
    },
  ],
  issues: [
    {
      referenceNo: 233,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 02",
      groupName: "Group ii",
      farmerID: 234,
      pondID: 234,
      fishSpecies: "Species 02",
      natureOfIssue: "Size of fish not as expected",
      remark: "...",
    },
    {
      referenceNo: 235,
      extensionAgent: "Agent 03",
      groupName: "Group iii",
      farmerID: 235,
      pondID: 235,
      fishSpecies: "Species 03",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 236,
      extensionAgent: "Agent 04",
      groupName: "Group iv",
      farmerID: 236,
      pondID: 236,
      fishSpecies: "Species 04",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 237,
      extensionAgent: "Agent 05",
      groupName: "Group v",
      farmerID: 237,
      pondID: 237,
      fishSpecies: "Species 05",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 238,
      extensionAgent: "Agent 06",
      groupName: "Group i",
      farmerID: 238,
      pondID: 238,
      fishSpecies: "Species 06",
      natureOfIssue: "Measurement challenge",
      remark: "...",
    },
    {
      referenceNo: 239,
      extensionAgent: "Agent 07",
      groupName: "Group ii",
      farmerID: 239,
      pondID: 239,
      fishSpecies: "Species 07",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 240,
      extensionAgent: "Agent 08",
      groupName: "Group iii",
      farmerID: 240,
      pondID: 240,
      fishSpecies: "Species 08",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 241,
      extensionAgent: "Agent 09",
      groupName: "Group iv",
      farmerID: 241,
      pondID: 241,
      fishSpecies: "Species 09",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 242,
      extensionAgent: "Agent 10",
      groupName: "Group v",
      farmerID: 242,
      pondID: 242,
      fishSpecies: "Species 10",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 243,
      extensionAgent: "Agent 11",
      groupName: "Group i",
      farmerID: 243,
      pondID: 243,
      fishSpecies: "Species 11",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 244,
      extensionAgent: "Agent 11",
      groupName: "Group ii",
      farmerID: 244,
      pondID: 244,
      fishSpecies: "Species 11",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
  ],
  remark: [
    {
      referenceNo: 233,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 02",
      groupName: "Group ii",
      farmerID: 234,
      pondID: 234,
      fishSpecies: "Species 02",
      natureOfIssue: "Size of fish not as expected",
      remark: "...",
    },
    {
      referenceNo: 235,
      extensionAgent: "Agent 03",
      groupName: "Group iii",
      farmerID: 235,
      pondID: 235,
      fishSpecies: "Species 03",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 236,
      extensionAgent: "Agent 04",
      groupName: "Group iv",
      farmerID: 236,
      pondID: 236,
      fishSpecies: "Species 04",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 237,
      extensionAgent: "Agent 05",
      groupName: "Group v",
      farmerID: 237,
      pondID: 237,
      fishSpecies: "Species 05",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 238,
      extensionAgent: "Agent 06",
      groupName: "Group i",
      farmerID: 238,
      pondID: 238,
      fishSpecies: "Species 06",
      natureOfIssue: "Measurement challenge",
      remark: "...",
    },
    {
      referenceNo: 239,
      extensionAgent: "Agent 07",
      groupName: "Group ii",
      farmerID: 239,
      pondID: 239,
      fishSpecies: "Species 07",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 240,
      extensionAgent: "Agent 08",
      groupName: "Group iii",
      farmerID: 240,
      pondID: 240,
      fishSpecies: "Species 08",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 241,
      extensionAgent: "Agent 09",
      groupName: "Group iv",
      farmerID: 241,
      pondID: 241,
      fishSpecies: "Species 09",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 242,
      extensionAgent: "Agent 10",
      groupName: "Group v",
      farmerID: 242,
      pondID: 242,
      fishSpecies: "Species 10",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 243,
      extensionAgent: "Agent 11",
      groupName: "Group i",
      farmerID: 243,
      pondID: 243,
      fishSpecies: "Species 11",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 244,
      extensionAgent: "Agent 11",
      groupName: "Group ii",
      farmerID: 244,
      pondID: 244,
      fishSpecies: "Species 11",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
  ],
  assign: [
    {
      referenceNo: 233,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 02",
      groupName: "Group ii",
      farmerID: 234,
      pondID: 234,
      fishSpecies: "Species 02",
      natureOfIssue: "Size of fish not as expected",
      remark: "...",
    },
    {
      referenceNo: 235,
      extensionAgent: "Agent 03",
      groupName: "Group iii",
      farmerID: 235,
      pondID: 235,
      fishSpecies: "Species 03",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 236,
      extensionAgent: "Agent 04",
      groupName: "Group iv",
      farmerID: 236,
      pondID: 236,
      fishSpecies: "Species 04",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 237,
      extensionAgent: "Agent 05",
      groupName: "Group v",
      farmerID: 237,
      pondID: 237,
      fishSpecies: "Species 05",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 238,
      extensionAgent: "Agent 06",
      groupName: "Group i",
      farmerID: 238,
      pondID: 238,
      fishSpecies: "Species 06",
      natureOfIssue: "Measurement challenge",
      remark: "...",
    },
    {
      referenceNo: 239,
      extensionAgent: "Agent 07",
      groupName: "Group ii",
      farmerID: 239,
      pondID: 239,
      fishSpecies: "Species 07",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 240,
      extensionAgent: "Agent 08",
      groupName: "Group iii",
      farmerID: 240,
      pondID: 240,
      fishSpecies: "Species 08",
      natureOfIssue: "Logistic challenge",
      remark: "...",
    },
    {
      referenceNo: 241,
      extensionAgent: "Agent 09",
      groupName: "Group iv",
      farmerID: 241,
      pondID: 241,
      fishSpecies: "Species 09",
      natureOfIssue: "Farmer not available",
      remark: "...",
    },
    {
      referenceNo: 242,
      extensionAgent: "Agent 10",
      groupName: "Group v",
      farmerID: 242,
      pondID: 242,
      fishSpecies: "Species 10",
      natureOfIssue: "Price differential",
      remark: "...",
    },
    {
      referenceNo: 243,
      extensionAgent: "Agent 11",
      groupName: "Group i",
      farmerID: 243,
      pondID: 243,
      fishSpecies: "Species 11",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
    {
      referenceNo: 244,
      extensionAgent: "Agent 11",
      groupName: "Group ii",
      farmerID: 244,
      pondID: 244,
      fishSpecies: "Species 11",
      natureOfIssue: "Others",
      remark: "...",
    },
    {
      referenceNo: 234,
      extensionAgent: "Agent 01",
      groupName: "Group i",
      farmerID: 233,
      pondID: 233,
      fishSpecies: "Species 01",
      natureOfIssue: "Offtaker did'nt show up",
      remark: "...",
    },
  ],
};

export default harvestData;
