export const GROUP_COLLECTION_PAYMENT = [
  {
    id: 1,
    GroupName: "Group i",
    GroupCollectionId: "GRPC0020",
    AccountTitle: "George Lindrof",
    AccountNo: 233454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Paid",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
  {
    id: 2,
    GroupName: "Group ii",
    GroupCollectionId: "GRPC0030",
    AccountTitle: "George Lindrof",
    AccountNo: 2334454,
    BankName: "NG Bank",
    AmountPayable: "2,00,000",
    StatementNo: 1232423,
    Status: "Payable",
    EditImgSrc: "http://localhost:8080/font/eva_edit-2-outline__2uyJm.svg",
    DeleteImgSrc: "http://localhost:8080/font/ri_delete-bin-2-fill__5Btdc.svg",
  },
];
