import pond1 from '../../assets/images/Pond ID 1.png'
import pond2 from '../../assets/images/Pond ID 2.png'
import pond3 from '../../assets/images/Pond ID 3.png'
import pond4 from '../../assets/images/Pond ID 4.png'
import pond5 from '../../assets/images/Pond ID 5.png'
import pond6 from '../../assets/images/Pond ID 6.png'
import pond7 from '../../assets/images/Pond ID 7.png'
import pond8 from '../../assets/images/Pond ID 8.png'

const data = [
    {
      farmerID: 1,
      farmerImg: pond1,
      pondID: 2321,
      prodSel: "Claris",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 2,
      farmerImg: pond2,
      pondID: 2321,
      prodSel: "Claris",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 3,
      farmerImg: pond3,
      pondID: 2321,
      prodSel: "Claris",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 4,
      farmerImg: pond4,
      pondID: 2321,
      prodSel: "Claris",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 5,
      farmerImg: pond5,
      pondID: 2321,
      prodSel: "Claris",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 6,
      farmerImg: pond6,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 7,
      farmerImg: pond2,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 8,
      farmerImg: pond7,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Juvenile",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 9,
      farmerImg: pond8,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: false,
      remarks: "...."
    },
    {
      farmerID: 10,
      farmerImg: pond1,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: false,
      remarks: "...."
    },
    {
      farmerID: 11,
      farmerImg: pond4,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
    {
      farmerID: 12,
      farmerImg: pond6,
      pondID: 2321,
      prodSel: "Hybrid",
      fishSize: "Fingerlings",
      pondSize: "60 * 45",
      fishOrigin: "OFNL Hatchery",
      startDate: "12-02-2020",
      endDate: "12-02-2020",
      GPS_Cord: "234,2345",
      trace: "Yes",
      active: true,
      remarks: "...."
    },
]

export default data