const SettingsData = {
    "recording": [
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 1,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 2,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
        {
            "companyName": "abcd",
            "ShortName": "aa",
            "companyID": 3,
            "companyCode": 222,
            "address": "kenea",
            "city": "lahore",
            "state": "NY",
            "zipCode": 44444,
            "accountType": "current",
            "countryCode": "+851",
            "checkForLicense": "verified",

        },
    ],
}

export default SettingsData
"Offtaker did'nt show up"
"Size of fish not as expected"
"Logistic challenge"
"Farmer not available"
"Price differential"
"Measurement challenge"
"Others"
