const outboundData = [
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },

    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },

    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
    {
      hostName: "Oluadepe",
      port: "5432",
      user: "George Lindrof",
      password: "*****",
      gender: "George Lindrof",
      testEmail: "Text Email",
    },
  ];
  
  export default outboundData;
  